on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [created, edited]
  pull_request:

name: Main

jobs:
  cache:
    uses: ./.github/workflows/cache.yaml
  run_tests:
    uses: ./.github/workflows/run_tests.yaml
    with:
      working-directory: ${{ needs.set_project_folder.outputs.project_folder }}
      KUBECONFIG: ${{ vars.KUBECONFIG }}
  package_and_release:
    if: github.event_name == 'release'
    uses: ./.github/workflows/package_and_release.yaml
  bump_brew:
    needs: package_and_release
    if: github.event_name == 'release'
    uses: ./.github/workflows/bump_brew.yaml
    secrets:
      TOKEN: ${{ secrets.HOMEBREW }}
