on:
  workflow_call:

name: "[reusable] rust test"
jobs:
 run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          cargo check
          cargo test --all  

