on:
  workflow_call:
    vars:
      KUBECONFIG:
        required: true

name: "[reusable] rust test"
jobs:
 run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ vars.KUBECONFIG }}
      - name: Test
        run: |
          cargo check
          cargo test --all
        env:
          KUBECONFIG: "/home/runner/.kube/config"

