on:
  workflow_call:
    inputs:
      KUBECONFIG:
        type: string
        required: true

name: "[reusable] rust test"
jobs:
 run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: tale/kubectl-action@v1
      - name: Test
        run: |
          cargo check
          cargo test --all

